AI_MAX_INTEL = 0
AI_MIN_INTEL = 10
AI_HIT_ZONE_MIN = 15
AI_HIT_ZONE_MAX = 25

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

PADDLE_WIDTH = 10
PADDLE_HEIGHT = 50
PADDLE_SPEED = 300

BALL_WIDTH = 10
BALL_HEIGHT = 10
BALL_SPEED = 200

FPS = 60

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN = (0, 255, 0)

PADDLE_GAP = 10

BAT_HIT_SND = 'bat_hit.wav'
WALL_HIT_SND = 'wall_hit.wav'
SCORE_SND = 'score_snd.wav'
POINT_LOST_SND = 'point_lost_snd.wav'

MUTE_INST_TEXT = "Press 'M' to mute the game."
START_INST_TEXT = "Press 'SPACE' to start a match."
MOVE_INST_TEXT = "Press 'UP' to move up and 'DOWN' to move down."
QUIT_INST_TEXT = "Press 'Q' to quit the game."

PADDLE1_START_X = SCREEN_WIDTH - PADDLE_WIDTH - PADDLE_GAP
PADDLE1_START_Y = SCREEN_HEIGHT / 2 - PADDLE_HEIGHT / 2

PADDLE2_START_X = 0 + PADDLE_GAP
PADDLE2_START_Y = SCREEN_HEIGHT / 2 - PADDLE_HEIGHT / 2

BALL_START_X = SCREEN_WIDTH / 2
BALL_START_Y = SCREEN_HEIGHT / 2

CAPTION_TEXT = "PONG"
